[36m[2023-07-11 00:02:03,923][233398] Environment ant, action_dim=8, obs_dim=87
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 599, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 349, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 190, in create_scheduler
    bounds[cfg.num_dims] = cfg.energy_bounds
IndexError: list assignment index out of range
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 599, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 349, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 190, in create_scheduler
    bounds[cfg.num_dims] = cfg.energy_bounds
IndexError: list assignment index out of range