
[36m[2023-07-23 12:10:18,412][287207] Environment humanoid, action_dim=17, obs_dim=227
bounds:
[(0.0, 1.0), (0.0, 1.0), (0.0, 16.0)]
using cvt archive
no kmeans
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 603, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 349, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 258, in create_scheduler
    result_archive = GridArchive(solution_dim=solution_dim,
  File "/home/icaros/Documents/PPGA/pyribs/ribs/archives/_grid_archive.py", line 66, in __init__
    ArchiveBase.__init__(
  File "/home/icaros/Documents/PPGA/pyribs/ribs/archives/_archive_base.py", line 170, in __init__
    self._solution_arr = np.empty((self._cells, solution_dim),
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 44.6 GiB for an array with shape (125000, 47906) and data type float64
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 603, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 349, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 258, in create_scheduler
    result_archive = GridArchive(solution_dim=solution_dim,
  File "/home/icaros/Documents/PPGA/pyribs/ribs/archives/_grid_archive.py", line 66, in __init__
    ArchiveBase.__init__(
  File "/home/icaros/Documents/PPGA/pyribs/ribs/archives/_archive_base.py", line 170, in __init__
    self._solution_arr = np.empty((self._cells, solution_dim),
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 44.6 GiB for an array with shape (125000, 47906) and data type float64