cuda enabled: True
action shape: (6,), prod shape: 6
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/RL/train_ppo.py", line 186, in <module>
    alg = PPO(cfg)
  File "/home/icaros/Documents/PPGADev/RL/ppo.py", line 89, in __init__
    self.obs = torch.zeros(
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 43352064000 bytes. Error code 12 (Cannot allocate memory)
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/RL/train_ppo.py", line 186, in <module>
    alg = PPO(cfg)
  File "/home/icaros/Documents/PPGADev/RL/ppo.py", line 89, in __init__
    self.obs = torch.zeros(
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 43352064000 bytes. Error code 12 (Cannot allocate memory)